### ISSUE TITLE
Save after refresh

### ISSUE THREAD

**Issue by lozinska** [manekenpix/miniNote#1]
I have notice that the updates are not saved automatically after refreshing the page, unless i press Ctrl+X. I would like to fix this issue by adding saving feature after the page has been refreshed and Ctrl+x was not pressed

**Comment by manekenpix** [comment]
Thank you, but I'm not sure if that's really necessary. If you automate saving, there's no need to press Ctrl+x anymore, so the my saving feature would be useless.

**Comment by manekenpix** [comment]
@lozinska  Saving to disk or adding some CSS would be very welcome!

**Comment by lozinska** [comment]
I would like to add a line of text that will notify user about the short cut that in order to save the info that has been typed.

**Comment by manekenpix** [comment]
Awesome, go ahead!

**Comment by manekenpix** [comment]
Could you open a new issue for that? I'll close this one
