### ISSUE TITLE
Adding a line to inform user about the Ctrl+X short cut

### ISSUE THREAD

**Issue by lozinska** [manekenpix/miniNote#4]
Would like to add one line where it will say about the shortcut that saves the updated note

**Comment by manekenpix** [comment]
That'd be a nice feature to have, thank you!

**Comment by lozinska** [comment]
I understand. Ok sure will do

**Comment by lozinska** [comment]
Hi there! I try to update gitHub repository so I will have same files as you but I'm not sure how does it works. Can you please let me know how can i update it

**Comment by manekenpix** [comment]
> Hi there! I try to update gitHub repository so I will have same files as you but I'm not sure how does it works. Can you please let me know how can i update it. Thank you

No problem at all. You can follow the steps that we saw in class this week to add a remote, in this case it would be something like:

`git remote add manekenpix git@github.com:manekenpix/miniNote.git`

then `git fetch --all`

now, to update your local master with the remote master
`git checkout master`
`git merge manekenpix`

After this, your local master will have all the changes in my master, and you can work with those changes.
I hope this helps you!

**Comment by lozinska** [comment]
Thank you for your reply, I think i missed out on that part. Indeed i just
delete repository from my profile and fork it from you again. I know its
not the best way to do that. Indeed i already send you the Pull Request.
Can you please confirm if you can see that or no. Thank you

сб, 21 сент. 2019 г. в 23:24, Josue <notifications@github.com>:
