### ISSUE TITLE
Being greeted with an error message 

### ISSUE THREAD

**Issue by zufishanali** [manekenpix/miniNote#9]
Hi Josue, 

I enjoyed using your application. However, I noticed that upon entry to the web-page, the user is greeted with a "could not load data" message. If you would like, I can add a fix and also set a New Note by default? 

<img width="858" alt="image1" src="https://user-images.githubusercontent.com/28423205/65555662-3a6eac80-defb-11e9-8c82-36a6c129ac2c.png">

Regards, 
Zufishan

**Comment by manekenpix** [comment]
Sorry about the late response. Yes go ahead!
